# Generated by Django 5.1.4 on 2026-03-29 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('satellite_id', models.CharField(max_length=20, unique=True)),
                ('orbit_type', models.CharField(default='LEO', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('standby', 'Standby'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='standby', max_length=20)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('attitude', 'Attitude Control'), ('power', 'Power Control'), ('thermal', 'Thermal Control'), ('payload', 'Payload Operation'), ('communication', 'Communication'), ('orbit', 'Orbit Control'), ('maintenance', 'Maintenance')], max_length=20)),
                ('command_code', models.CharField(max_length=50)),
                ('parameters', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('operator', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='satellite.satellite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_battery', models.FloatField()),
                ('temperature_solar_panel', models.FloatField()),
                ('temperature_payload', models.FloatField()),
                ('voltage_bus', models.FloatField()),
                ('current_bus', models.FloatField()),
                ('power_generation', models.FloatField()),
                ('attitude_roll', models.FloatField(default=0.0)),
                ('attitude_pitch', models.FloatField(default=0.0)),
                ('attitude_yaw', models.FloatField(default=0.0)),
                ('health_status', models.CharField(choices=[('nominal', 'Nominal'), ('warning', 'Warning'), ('critical', 'Critical')], default='nominal', max_length=20)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='satellite.satellite')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
